# Generated by Django 4.1.3 on 2022-11-16 14:33

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Company")),
                ("tax_id", models.CharField(max_length=155, verbose_name="Tax ID")),
                ("website", models.URLField(verbose_name="Website")),
                (
                    "industry_id",
                    models.CharField(
                        choices=[
                            ("", "--- Select Industry ---"),
                            ("AFSA", "Accommodation and Food Service Activities"),
                            ("IC", "Information and Communication"),
                            ("IT", "Information Technology"),
                            (
                                "EGSACS",
                                "Electricity, Gas, Steam and Air Conditioning Supply",
                            ),
                            ("CONST", "Construction"),
                            ("ASSA", "Administrative and Support Service Activities"),
                            (
                                "PSTA",
                                "Professional, Scientific and Technical Activities",
                            ),
                            ("MANU", "Manufacturing"),
                            ("WRT", "Wholesale and Retail Trade"),
                            ("REA", "Real Estate Activities"),
                            (
                                "WSSWMRA",
                                "Water Supply; Sewerage, Waste Management and Remediation Activities",
                            ),
                            ("MQ", "Mining and Quarrying"),
                            ("TS", "Transportation and Storage"),
                        ],
                        max_length=100,
                    ),
                ),
                ("logo_company", models.ImageField(default="", upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Phone number"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "image_person",
                    models.ImageField(blank=True, default="", upload_to="upload/"),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.companies",
                    ),
                ),
            ],
        ),
    ]
