# Generated by Django 4.1.3 on 2022-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="image_person",
            field=models.ImageField(
                blank=True, default="", upload_to="static/uploads/"
            ),
        ),
    ]
