# Generated by Django 4.1.3 on 2022-11-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_partner_image_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="image_person",
            field=models.ImageField(
                blank=True, default="", upload_to="crm/static/uploads/"
            ),
        ),
    ]
