# Generated by Django 4.1.3 on 2022-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_companies_logo_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companies",
            name="logo_company",
            field=models.ImageField(
                blank=True, default="", upload_to="static/uploads/"
            ),
        ),
    ]
