# Generated by Django 4.1.3 on 2023-01-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_alter_partner_image_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companies",
            name="tax_id",
            field=models.CharField(blank=True, max_length=155, verbose_name="Tax ID"),
        ),
        migrations.AlterField(
            model_name="companies",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
