# Generated by Django 4.1.3 on 2022-11-16 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Months",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Stage Name")),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Opportunity")),
                (
                    "expect_revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Expected Revenue"
                    ),
                ),
                ("date_deadline", models.DateField(verbose_name="Expected Closing")),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.companies",
                    ),
                ),
                (
                    "partner_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.partner",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.stage",
                    ),
                ),
            ],
            options={"db_table": "Lead",},
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                check=models.Q(("expect_revenue__gte", "0")),
                name="lead_expect_non_negative",
            ),
        ),
    ]
