# Generated by Django 4.1.3 on 2022-11-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="lead", table=None,),
    ]
