# Generated by Django 4.1.3 on 2022-11-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_lead_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
    ]
