# Generated by Django 4.1.3 on 2023-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_lead_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=600)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
