# Generated by Django 4.1.3 on 2023-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_menus"),
    ]

    operations = [
        migrations.AddField(
            model_name="menus", name="position", field=models.IntegerField(default=0),
        ),
    ]
